# Dataset

In [12]:
import numpy as np  
import pandas as pd 
import seaborn as sns
import os
import matplotlib.pyplot as plt

## 1. Data Collection 
### Read Data

In [13]:
path = "../data"
res = os.listdir(path)
sorted(res)

['.DS_Store',
 'EV_Population.csv',
 'EV_PopulationByCounty.csv',
 'counties-albers-10m.json',
 'countries-10m.json',
 'pop.json',
 'population.json',
 'unemployment.csv']

In [14]:
dfpop = pd.read_csv(os.path.join(path, 'EV_population.csv'))
dfpop.head()

,VIN (1-10),County,City,State,Postal Code,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,Electric Range,Base MSRP,Legislative District,DOL Vehicle ID,Electric Utility,2020 Census Tract,latitude,longtitude
0,5UXTA6C05P,Yakima,Yakima,WA,98903,2023,BMW,X5,Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,30,0,14,227153587,PACIFICORP,53077002803,-120.477805,46.553505
1,5YJSA1E24G,King,Seattle,WA,98103,2016,TESLA,MODEL S,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,210,0,43,187728201,CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),53033004902,-122.343010,47.659185
2,1N4AZ1CP5J,King,Shoreline,WA,98177,2018,NISSAN,LEAF,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,151,0,32,249867971,CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),53033020100,-122.382425,47.772790
3,5YJ3E1EA6J,Island,Coupeville,WA,98239,2018,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,215,0,10,223792649,PUGET SOUND ENERGY INC,53029971100,-122.688071,48.217998
4,1G1FW6S00H,Kitsap,Seabeck,WA,98380,2017,CHEVROLET,BOLT EV,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,238,0,35,125032974,PUGET SOUND ENERGY INC,53035091301,-122.847462,47.638360

In [15]:
dfpop.columns

Index(['VIN (1-10)', 'County', 'City', 'State', 'Postal Code', 'Model Year',
       'Make', 'Model', 'Electric Vehicle Type',
       'Clean Alternative Fuel Vehicle (CAFV) Eligibility', 'Electric Range',
       'Base MSRP', 'Legislative District', 'DOL Vehicle ID',
       'Electric Utility', '2020 Census Tract', 'latitude', 'longtitude'],
      dtype='object')

In [16]:

df_out = dfpop[['County', 'City', 'State', 'Postal Code', 'Model Year',
       'Make', 'Model', 'Electric Vehicle Type', 'DOL Vehicle ID', 'latitude', 'longtitude']]

df_dict = df_out.to_json(orient='records', indent=2)
with open(os.path.join(path, 'population.json'), 'w') as f:
    f.write(df_dict)

In [79]:
df_out

,County,City,State,Postal Code,Model Year,Make,Model,Electric Vehicle Type,DOL Vehicle ID,latitude,longtitude
0,Yakima,Yakima,WA,98903,2023,BMW,X5,Plug-in Hybrid Electric Vehicle (PHEV),227153587,-120.477805,46.553505
1,King,Seattle,WA,98103,2016,TESLA,MODEL S,Battery Electric Vehicle (BEV),187728201,-122.343010,47.659185
2,King,Shoreline,WA,98177,2018,NISSAN,LEAF,Battery Electric Vehicle (BEV),249867971,-122.382425,47.772790
3,Island,Coupeville,WA,98239,2018,TESLA,MODEL 3,Battery Electric Vehicle (BEV),223792649,-122.688071,48.217998
4,Kitsap,Seabeck,WA,98380,2017,CHEVROLET,BOLT EV,Battery Electric Vehicle (BEV),125032974,-122.847462,47.638360
...,...,...,...,...,...,...,...,...,...,...,...
153482,San Juan,Eastsound,WA,98245,2013,NISSAN,LEAF,Battery Electric Vehicle (BEV),154379130,-122.907229,48.701672
153483,Spokane,Spokane,WA,99223,2017,TESLA,MODEL S,Battery Electric Vehicle (BEV),204991475,-117.369705,47.626370
153484,King,Seatac,WA,98188,2023,CHEVROLET,BOLT EV,Battery Electric Vehicle (BEV),244720059,-122.291790,47.434730
153485,King,Kent,WA,98031,2021,FORD,MUSTANG MACH-E,Battery Electric Vehicle (BEV),186104215,-122.201252,47.393181
153486,Pierce,Tacoma,WA,98407,2013,NISSAN,LEAF,Battery Electric Vehicle (BEV),153724504,-122.511336,47.292383

# convert

In [62]:
# dfpop['State'] = 'Washington'

dfpop['County'].unique()

array(['Yakima', 'King', 'Island', 'Kitsap', 'Snohomish', 'Thurston',
       'Clark', 'Whitman', 'Grant', 'Stevens', 'Chelan', 'Walla Walla',
       'Spokane', 'Kittitas', 'Pierce', 'Skagit', 'Douglas', 'Cowlitz',
       'Clallam', 'Jefferson', 'Lewis', 'Benton', 'Whatcom', 'Klickitat',
       'Pend Oreille', 'Mason', 'Ferry', 'Skamania', 'Grays Harbor',
       'Franklin', 'San Juan', 'Okanogan', 'Adams', 'Asotin', 'Pacific',
       'Wahkiakum', 'Columbia', 'Lincoln', 'Garfield'], dtype=object)

In [63]:
df_comp = pd.read_csv('../data/unemployment.csv')
df_comp.head()

     id    state          county  rate
0  1001  Alabama  Autauga County   5.1
1  1003  Alabama  Baldwin County   4.9
2  1005  Alabama  Barbour County   8.6
3  1007  Alabama     Bibb County   6.2
4  1009  Alabama   Blount County   5.1

In [64]:
df_wcounty = df_comp[df_comp['state'] == 'Washington']

In [65]:
# aggregate by County and count the number of records
df_newd = dfpop.groupby('County').agg({'DOL Vehicle ID': 'count'})

In [70]:
df_newd = df_newd.reset_index()
df_newd['county'] = df_newd['County'] + ' County'

df_newd['count'] = df_newd['DOL Vehicle ID']

In [73]:
df_out_c = df_newd.merge(df_wcounty, on='county')

In [74]:
df_out_c

,index,County,DOL Vehicle ID,county,count,id,state,rate
0,0,Adams,43,Adams County,43,53001,Washington,4.8
1,1,Asotin,65,Asotin County,65,53003,Washington,4.7
2,2,Benton,1860,Benton County,1860,53005,Washington,6.5
3,3,Chelan,892,Chelan County,892,53007,Washington,5.1
4,4,Clallam,929,Clallam County,929,53009,Washington,7.6
5,5,Clark,9061,Clark County,9061,53011,Washington,6.6
6,6,Columbia,17,Columbia County,17,53013,Washington,5.9
7,7,Cowlitz,780,Cowlitz County,780,53015,Washington,7.6
8,8,Douglas,304,Douglas County,304,53017,Washington,6.6
9,9,Ferry,26,Ferry County,26,53019,Washington,9.8
10,10,Franklin,515,Franklin County,515,53021,Washington,6.5
11,11,Garfield,3,Garfield County,3,53023,Washington,5.3
12,12,Grant,480,Grant County,480,53025,Washington,6.6
13,13,Grays Harbor,544,Grays Harbor County,544,53027,Washington,8.7
14,14,Island,1673,Island County,1673,53029,Washington,6.0
15,15,Jefferson,886,Jefferson County,886,53031,Washington,7.2
16,16,King,80637,King County,80637,53033,Washington,3.9
17,17,Kitsap,5079,Kitsap County,5079,53035,Washington,5.9
18,18,Kittitas,512,Kittitas County,512,53037,Washington,5.8
19,19,Klickitat,254,Klickitat County,254,53039,Washington,6.5
20,20,Lewis,634,Lewis County,634,53041,Washington,8.1
21,21,Lincoln,40,Lincoln County,40,53043,Washington,4.1
22,22,Mason,717,Mason County,717,53045,Washington,8.3
23,23,Okanogan,212,Okanogan County,212,53047,Washington,6.1
24,24,Pacific,182,Pacific County,182,53049,Washington,7.7
25,25,Pend Oreille,46,Pend Oreille County,46,53051,Washington,8.9
26,26,Pierce,11804,Pierce County,11804,53053,Washington,6.5
27,27,San Juan,865,San Juan County,865,53055,Washington,3.9
28,28,Skagit,1713,Skagit County,1713,53057,Washington,6.7
29,29,Skamania,167,Skamania County,167,53059,Washington,6.7
30,30,Snohomish,17727,Snohomish County,17727,53061,Washington,4.3
31,31,Spokane,3820,Spokane County,3820,53063,Washington,6.3
32,32,Stevens,195,Stevens County,195,53065,Washington,7.9
33,33,Thurston,5514,Thurston County,5514,53067,Washington,5.9
34,34,Wahkiakum,51,Wahkiakum County,51,53069,Washington,8.4
35,35,Walla Walla,376,Walla Walla County,376,53071,Washington,5.6
36,36,Whatcom,3747,Whatcom County,3747,53073,Washington,6.3
37,37,Whitman,273,Whitman County,273,53075,Washington,5.5
38,38,Yakima,844,Yakima County,844,53077,Washington,7.3

In [75]:
df_ouput_county = df_out_c[['id', 'state', 'county', 'DOL Vehicle ID']]

In [76]:
df_ouput_county.columns = ['id', 'state', 'county', 'rate']

In [77]:
df_ouput_county

       id       state               county   rate
0   53001  Washington         Adams County     43
1   53003  Washington        Asotin County     65
2   53005  Washington        Benton County   1860
3   53007  Washington        Chelan County    892
4   53009  Washington       Clallam County    929
5   53011  Washington         Clark County   9061
6   53013  Washington      Columbia County     17
7   53015  Washington       Cowlitz County    780
8   53017  Washington       Douglas County    304
9   53019  Washington         Ferry County     26
10  53021  Washington      Franklin County    515
11  53023  Washington      Garfield County      3
12  53025  Washington         Grant County    480
13  53027  Washington  Grays Harbor County    544
14  53029  Washington        Island County   1673
15  53031  Washington     Jefferson County    886
16  53033  Washington          King County  80637
17  53035  Washington        Kitsap County   5079
18  53037  Washington      Kittitas County    512
19  53039  Washington     Klickitat County    254
20  53041  Washington         Lewis County    634
21  53043  Washington       Lincoln County     40
22  53045  Washington         Mason County    717
23  53047  Washington      Okanogan County    212
24  53049  Washington       Pacific County    182
25  53051  Washington  Pend Oreille County     46
26  53053  Washington        Pierce County  11804
27  53055  Washington      San Juan County    865
28  53057  Washington        Skagit County   1713
29  53059  Washington      Skamania County    167
30  53061  Washington     Snohomish County  17727
31  53063  Washington       Spokane County   3820
32  53065  Washington       Stevens County    195
33  53067  Washington      Thurston County   5514
34  53069  Washington     Wahkiakum County     51
35  53071  Washington   Walla Walla County    376
36  53073  Washington       Whatcom County   3747
37  53075  Washington       Whitman County    273
38  53077  Washington        Yakima County    844

In [78]:
df_ouput_county.to_csv('../data/une.csv', index=None)